### ISSUE TITLE
Syntax highlighting on folds

### ISSUE THREAD

**Issue by ranebrown** [kevinhwang91/nvim-ufo#35] opened 2022-07-03 14:30 UTC
### Neovim version (nvim -v | head -n1)

v0.8.0-dev+513-g01fc5097d

### Operating system/version

macOS 12.4

### How to reproduce the issue

1. Open file and syntax highlighting does not penetrate folds.
2. `:TSBufDisable highlight`
3. Open/close folds to refresh and highlighting appears.

### Expected behavior

Syntax highlighting on folds while using treesitter highlighting.

### Actual behavior

Highlighting only shows up after disabling treesitter highlighting and using regex i.e. `:TSBufDisable highlight`

**Comment by kevinhwang91** [comment] 2022-07-03 14:41
What's your treesitter parser?

`lua =require('vim.treesitter.highlighter').active[vim.api.nvim_get_current_buf()]`

**Comment by ranebrown** [comment] 2022-07-03 15:16
I've seen the same behavior with lua and cpp parsers.

<details>
  <summary>Output</summary>
  
```
 <1>{ =require('vim.treesitter.highlighter').active[vim.api.nvim_get_current_buf()]
  _highlight_states = {
    [<userdata 1>] = {
      iter = <function 1>,
      next_row = 48
    }
  },
  _queries = {
    cpp = {
      _query = {
        captures = <2>{ "variable", "keyword", "keyword.operator", "keyword.return", "repeat", "conditio
nal", "constant.macro", "include", "operator", "boolean", "punctuation.delimiter", "punctuation.special"
, "punctuation.bracket", "string", "string.escape", "constant.builtin", "number", "character", "function
.macro", "property", "_parent", "label", "type", "constant", "_u", "function", "comment", "parameter", "
attribute", "error", "field", "method", "namespace", "constructor", "function.builtin", "variable.builti
n", "exception" },
        info = {
          captures = <table 2>,
          patterns = {
            [23] = { { "not-has-parent?", 21, "template_method", "function_declarator", "call_expression
" } },
            [25] = { { "has-ancestor?", 20, "field_declaration" }, { "not-has-ancestor?", 20, "function_
declarator" } },
            [29] = { { "lua-match?", 24, "^[A-Z][A-Z0-9_]+$" } },
            [33] = { { "eq?", 25, "#undef" } },
            [44] = { { "match?", 31, "(^_|^m_|_$)" } },
            [50] = { { "has-parent?", 21, "template_method", "function_declarator", "call_expression" }
},
            [55] = { { "lua-match?", 23, "^[A-Z]" } },
            [56] = { { "lua-match?", 24, "^[A-Z][A-Z_0-9]*$" } },
            [63] = { { "lua-match?", 34, "^[A-Z]" } },
            [71] = { { "lua-match?", 34, "^[A-Z]" } },
            [72] = { { "lua-match?", 34, "^[A-Z]" } },
            [73] = { { "lua-match?", 34, "^[A-Z]" } },
            [74] = { { "lua-match?", 34, "^[A-Z]" } }
          }
        },
        query = <userdata 2>,
        <metatable> = <3>{
          __index = <table 3>,
          apply_directives = <function 2>,
          iter_captures = <function 3>,
          iter_matches = <function 4>,
          match_preds = <function 5>
        }
      },
      hl_cache = { 984,
        [5] = 990,
        [6] = 992,
        [9] = 989,
                [11] = 988,
        [13] = 986,
        [17] = 991,
        [23] = 983,
        [26] = 985,
        [28] = 987,
        [30] = 993,
        <metatable> = {
          __index = <function 6>
        }
      },
      <metatable> = {
        __index = <4>{
          __index = <table 4>,
          _get_hl_from_capture = <function 7>,
          new = <function 8>,
          query = <function 9>
        }
      }
    }
  },
  bufnr = 1,
  edit_count = 0,
  line_count = {},
  redraw_count = 11,
  tree = {
    _callbacks = {
      bytes = { <function 10> },
      changedtree = { <function 11> },
      child_added = {},
      child_removed = {},
      detach = { <function 12> }
    },
    _children = {},
    _injection_query = {
      captures = <5>{ "cpp", "comment" },
      info = {
        captures = <table 5>,
        patterns = {}
      },
      query = <userdata 3>,
      <metatable> = <table 3>
    },
    _lang = "cpp",
    _opts = {},
    _parser = <userdata 4>,
    _regions = {},
    _source = 1,
    _trees = { <userdata 1> },
    _valid = true,
    <metatable> = <6>{
      __index = <table 6>,
      _do_callback = <function 13>,
      _get_injections = <function 14>,
      _on_bytes = <function 15>,
      _on_detach = <function 16>,
      _on_reload = <function 17>,
      add_child = <function 18>,
      children = <function 19>,
      contains = <function 20>,
      destroy = <function 21>,
      for_each_child = <function 22>,
      for_each_tree = <function 23>,
      included_regions = <function 24>,
      invalidate = <function 25>,
      is_valid = <function 26>,
      lang = <function 27>,
      language_for_range = <function 28>,
      new = <function 29>,
      parse = <function 30>,
      register_cbs = <function 31>,
      remove_child = <function 32>,
      set_included_regions = <function 33>,
      source = <function 34>,
      trees = <function 35>
    }
  },
  <metatable> = <7>{
    __index = <table 7>,
    _on_buf = <function 36>,
    _on_line = <function 37>,
    _on_win = <function 38>,
    active = { <table 1> },
    destroy = <function 39>,
    get_highlight_state = <function 40>,
    get_query = <function 41>,
    hl_map = {
      annotation = "TSAnnotation",
      attribute = "TSAttribute",
      boolean = "TSBoolean",
      character = "TSCharacter",
      ["character.special"] = "TSCharacterSpecial",
      comment = "TSComment",
      conditional = "TSConditional",
      constant = "TSConstant",
      ["constant.builtin"] = "TSConstBuiltin",
      ["constant.macro"] = "TSConstMacro",
      constructor = "TSConstructor",
      debug = "TSDebug",
      define = "TSDefine",
      error = "TSError",
      exception = "TSException",
      field = "TSField",
      float = "TSFloat",
      function = "TSFunction",
      ["function.builtin"] = "TSFuncBuiltin",
      ["function.macro"] = "TSFuncMacro",
      ["function.special"] = "Function",
      include = "TSInclude",
      keyword = "TSKeyword",
      ["keyword.function"] = "TSKeywordFunction",
      ["keyword.operator"] = "TSKeywordOperator",
      ["keyword.return"] = "TSKeywordReturn",
      label = "TSLabel",
      macro = "Macro",
      method = "TSMethod",
      namespace = "TSNamespace",
      none = "TSNone",
      number = "TSNumber",
      operator = "TSOperator",
      parameter = "TSParameter",
      ["parameter.reference"] = "TSParameterReference",
      preproc = "TSPreProc",
      property = "TSProperty",
      ["punctuation.bracket"] = "TSPunctBracket",
      ["punctuation.delimiter"] = "TSPunctDelimiter",
      ["punctuation.special"] = "TSPunctSpecial",
      repeat = "TSRepeat",
      storageclass = "TSStorageClass",
      string = "TSString",
      ["string.escape"] = "TSStringEscape",
      ["string.regex"] = "TSStringRegex",
      ["string.special"] = "TSStringSpecial",
      structure = "Structure",
      symbol = "TSSymbol",
      tag = "TSTag",
      ["tag.attribute"] = "TSTagAttribute",
      ["tag.delimiter"] = "TSTagDelimiter",
      text = "TSText",
      ["text.danger"] = "TSDanger",
      ["text.emphasis"] = "TSEmphasis",
      ["text.environment"] = "TSEnvironment",
      ["text.environment.name"] = "TSEnvironmentName",
      ["text.literal"] = "TSLiteral",
      ["text.math"] = "TSMath",
      ["text.note"] = "TSNote",
      ["text.reference"] = "TSTextReference",
      ["text.strike"] = "TSStrike",
      ["text.strong"] = "TSStrong",
      ["text.title"] = "TSTitle",
      ["text.underline"] = "TSUnderline",
      ["text.uri"] = "TSURI",
      ["text.warning"] = "TSWarning",
      todo = "TSTodo",
      type = "TSType",
      ["type.builtin"] = "TSTypeBuiltin",
      ["type.definition"] = "TSTypeDefinition",
      ["type.qualifier"] = "TSTypeQualifier",
      variable = "TSVariable",
      ["variable.builtin"] = "TSVariableBuiltin",
      <metatable> = {
        __index = <function 42>
      }
    },
    new = <function 43>,
    on_bytes = <function 44>,
    on_changedtree = <function 45>,
    on_detach = <function 46>,
    reset_highlight_state = <function 47>
  }
}
```
</details>

**Comment by kevinhwang91** [comment] 2022-07-03 15:20
can't reproduce, use a minimal config about treesitter please.

**Comment by jaschenb** [comment] 2022-07-03 20:15
I have a similar problem. It seems the treesitter provider takes the highlights from syntax or something. I have a custom colorscheme and it displays the 'normal' highlights like String correctly, however things like TSVariable are white as soon as I close the fold. I tried to look into things yesterday, but I'm also not familiar with Treesitter to much, so I couldn't figure out, where to look for the highlight groups your plugin returns.

**Comment by ranebrown** [comment] 2022-07-03 20:37
I was deleting plugins to try and find what might be causing the issue and I'm not seeing the behavior anymore after re-enabling everything. I'm wondering if there were some old treesitter queries laying around causing issues. I'll report back if I figure out what was causing the issue but seems ok for me now.

**Comment by kevinhwang91** [comment] 2022-07-04 01:42
> I have a similar problem. It seems the treesitter provider takes the highlights from syntax or something. I have a custom colorscheme and it displays the 'normal' highlights like String correctly, however things like TSVariable are white as soon as I close the fold. I tried to look into things yesterday, but I'm also not familiar with Treesitter to much, so I couldn't figure out, where to look for the highlight groups your plugin returns.

https://github.com/kevinhwang91/nvim-ufo/blob/98b07fc2606c40ae5bf0eaf67e74d8b82a69f040/lua/ufo/render/treesitter.lua#L42

**Comment by kevinhwang91** [comment] 2022-07-04 09:18
close the issue, ping me it has been reproduced.

**Closed by kevinhwang91** 2022-07-04 09:18 UTC
Labels: bug
