### ISSUE TITLE
how can i exclude some filetypes

### ISSUE THREAD

**Issue by Aneeqasif** [kevinhwang91/nvim-ufo#122] opened 2023-03-28 03:32 UTC
### Feature description

i use nvdash and in it i can use
M.blankline = {
  indentLine_enabled = 1,
  filetype_exclude = {
    "help",
    "terminal",
    "lazy",
    "lspinfo",
    "TelescopePrompt",
    "TelescopeResults",
    "mason",
    "nvdash",
    "nvcheatsheet",
    "",
  },

how can i do it for this pluging 

### Describe the solution you'd like

exclude some filetype let say nvdash

### Additional context

![image](https://user-images.githubusercontent.com/78728701/228121062-0c8eafd2-ed89-4289-ae74-7b8dcdf7b9cc.png)

**Comment by rockyzhang24** [comment] 2023-03-28 04:12
Duplicate of https://github.com/kevinhwang91/nvim-ufo/issues/33

**Closed** 2023-03-28 04:15 UTC
Labels: enhancement
