### ISSUE TITLE
UnhandledPromiseRejection in nightly Neovim

### ISSUE THREAD

**Issue by MariaSolOs** [kevinhwang91/nvim-ufo#162] opened 2023-09-19 20:14 UTC
### Neovim version (nvim -v | head -n1)

NVIM v0.10.0-dev-1152+g5a363ccac

### Operating system/version

Mac Ventura 13.5.2

### How to reproduce the issue

1. Write the following configuration file in `repro.lua`:
```lua
-- Setting
vim.o.foldcolumn = "1"
vim.o.foldlevel = 99
vim.o.foldlevelstart = -1
vim.o.foldenable = true

local root = vim.fn.fnamemodify("./.repro", ":p")
for _, name in ipairs { "config", "data", "state", "cache" } do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system {
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  }
end
vim.opt.runtimepath:prepend(lazypath)

local plugins = {
  "kevinhwang91/promise-async",
  "kevinhwang91/nvim-ufo",
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

local ufo = require "ufo"
ufo.setup()
vim.keymap.set("n", "zR", ufo.openAllFolds)
vim.keymap.set("n", "zM", ufo.closeAllFolds)

```

2. Open `neovim` with `nvim --clean -u repro.lua repro.lua`.
3. Open `:messages`.

### Expected behavior

For this plugin to work as expected with no errors.

### Actual behavior

The following error appears:

```
Error executing vim.schedule lua callback: UnhandledPromiseRejection with the reason:                                                                                                        
...osolano/.local/share/nvim/lazy/nvim-ufo/lua/ufo/wffi.lua:13: dlsym(RTLD_DEFAULT, find_window_by_handle): symbol not found   
```

**Comment by MariaSolOs** [comment] 2023-09-19 22:18
Also interestingly enough, I can use reproduce this when using the `Release` or `RelWithDebInfo` Neovim builds, but not with the `Debug` one.

**Comment by MariaSolOs** [comment] 2023-09-19 22:18
cc @bfredl

**Comment by kevinhwang91** [comment] 2023-09-19 22:35
Can't reproduce it under Linux build with `Release`, looks like your platform issue or cache of build issue.
You can disable `jit`  in pre-processing for `require'ufo'.setup` and enable it in post-processing to force ufo to use normal api to add folds.
Like:
```lua
local bak = jit
jit = nil
ufo.setup()
jit = bak
```

**Comment by MariaSolOs** [comment] 2023-09-19 22:43
@kevinhwang91 Alright that hack seems to work. Are there any unexpected consequences of using that?

**Comment by kevinhwang91** [comment] 2023-09-19 22:48
It's slow and may block if the provider produces a lot of fold ranges. Using `ffi` will get better performance.

**Comment by rockyzhang24** [comment] 2023-09-20 14:09
I can't reproduce it. 

M1 (ARM) chip
macOS Ventura 13.5.2
NVIM v0.10.0-dev-1046+g3afbf4745

**Comment by MariaSolOs** [comment] 2023-09-20 16:37
@rockyzhang24 it doesn't seem that you're on the latest nightly.

**Comment by rockyzhang24** [comment] 2023-09-20 16:55
Just now I rebuilt nvim with the latest commit, and still no errors.

NVIM v0.10.0-dev-1164+g23c21e763

**Comment by MariaSolOs** [comment] 2023-09-20 17:16
@rockyzhang24 interesting. The only other thing I can think about is that I install Neovim under `$HOME/neovim`, not the default location. It would be weird for that to matter though.

**Comment by ecosse3** [comment] 2023-09-20 22:22
I have the same issue on master branch of neovim.

```
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
```

**Comment by dundargoc** [comment] 2023-09-21 20:09
I'm pretty sure this should now be fixed on neovim master. Lemme know if it still doesn't work please.

**Comment by MariaSolOs** [comment] 2023-09-21 20:20
@dundargoc works for me, thank you!

**Closed** 2023-09-21 20:19 UTC
Labels: bug
